# Generated by Django 5.1.4 on 2025-01-11 15:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userbankaccount_account_type'),
        ('transactions', '0008_alter_transaction_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBankAccount',
            new_name='UserAccount',
        ),
    ]
