# Generated by Django 5.1.4 on 2025-01-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='loan_approve',
        ),
    ]
