# Generated by Django 5.1.4 on 2025-01-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_remove_transaction_loan_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Return'), (3, 'Borrow'), (4, 'BORROW Paid'), (5, 'Transfer')], null=True),
        ),
    ]
